### ISSUE TITLE
EPIC - Login To User Account

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#15]
Our app needs a way for users to login. This feature will primarily constitute of frontend work since it will deal with the firebase on the frontend. The figma can be found [here](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=1102-5929&mode=design&t=TRygRg37gS6ygyVH-0)

Landing Page:
![Screenshot 2024-01-16 at 7 53 41 PM](https://github.com/TritonSE/PIA-Program-Manager/assets/85322002/a3eb5ca4-471b-4916-bbe5-a73e50d7f9e2)

In hindsight we need users to sign in via the landing page. Our app should then send our credentials to Firebase. Once we get confirmation that the credentials are correct and the auth token, we should route users to the home page. If a user has not been approved yet then we need to route them to a page indicating waiting for account approval.

Home Page:
<img width="377" alt="Screenshot 2024-01-13 at 11 09 49 AM" src="https://github.com/TritonSE/PIA-Program-Manager/assets/85322002/3376f409-b1a8-40a0-bb34-9b34fc874c9e">

Once login is successfully completed the last thing that needs to be done is to ensure our routes are protected. To do this you need to ensure that we send the auth token in the header of the route body. This is our way of telling our API that a valid user is accessing the routes.

Tasks:

- [x] #27
- [x] #38
- [ ] Get data for landing page from backend and ensure routing works
- [ ] Ensure that routes on the frontend use the auth token and that backend routes validate the auth token
- [ ] Add some function to the frontend that retrieves whether a user is a team/admin so that other pages can access that information
- [x] #60
