### ISSUE TITLE
EPIC - Add Students Form

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#17]
One of the most important functionalities of the portal is to be able to add new students. This is done through a form which then sends the data to our RestAPI to be updated on MongoDb. Take special note of the different fields that need to be filled out. The figma designs can be found [here.](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=1034-6627&mode=design&t=TRygRg37gS6ygyVH-0)

![Screenshot 2024-01-10 at 12 40 43 AM](https://github.com/TritonSE/PIA-Program-Manager/assets/85322002/a22edf6a-77c4-4b3d-bc14-cce107ff5cdd)

Tasks

- [x] [Add a backend route that allows you to add all necessary information about a student](https://github.com/TritonSE/PIA-Program-Manager/issues/8)
- [x] Create the UI for the form (including the add student button)
- [x] Ensure that data is sent from Frontend to Backend and is updated
