### ISSUE TITLE
EPIC - Add Programs Form

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#20]
An important functionality of the app is to be able to add programs to the database. Programs represent the classes that students sign up for. For this feature we need a form to input data and our backend needs to update the data in our database. The figma designs can be found [here.](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=2020-9410&mode=design&t=WnlTGgLHoaEgPgqq-0)

Tasks:

- [x] [Create a backend route to add all necessary information about a program](https://github.com/TritonSE/PIA-Program-Manager/issues/9)
- [x] [Add a UI form for creating a new program](https://github.com/TritonSE/PIA-Program-Manager/issues/30)
- [x] Connect Frontend and Backend, ensure that data inputted on frontend is stored on backend
