### ISSUE TITLE
EPIC - Miscellaneous

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#23]
The epic is mainly used to list tasks that don't particularly fit into a single feature but are important for the overall app.

- [x] [Side Bar component and Main page routing](https://github.com/TritonSE/PIA-Program-Manager/issues/5)
- [x] [Frontend API CRUD routes](https://github.com/TritonSE/PIA-Program-Manager/issues/6)
- [x] [Components - Input Fields](https://github.com/TritonSE/PIA-Program-Manager/issues/4)
- [x] [Components - Buttons](https://github.com/TritonSE/PIA-Program-Manager/issues/3)
- [x] [Auth Layer Middleware Function](https://github.com/TritonSE/PIA-Program-Manager/issues/10)
- [x] #90
