### ISSUE TITLE
EPIC - New Account Approval

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#37]
## Description

We need a page to be able to approve accounts. This page will be known as the notifications tab. Note that only admins will be able to access this page. The process for how this will work is simple. First we will get all accounts that have not been approved. We will then display each account using the special cards shown on figma. Then users will have the option to accept or deny an account. In both cases we will want to send an email to that user indicating their approval status. If a user has been accepted then we need to modify their status state to be true on MongoDb. If a user is rejected then we need to delete the respective document on MongoDb and Firebase.

## Requirements

- [x] #41
- [ ] GET route to get all not approved accounts
- [ ] PATCH route to edit users account status (can be taken from edit user)
- [ ] DELETE route to delete a user on MongoDb and Firebase
- [x] #42
- [x] #58
