### ISSUE TITLE
[EPIC] - Program Profiles Page

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#74]
Description:

The V2 website has a new program profile page. This page is supposed to show all students that are associated with a particular program and display it in a table format. Morever, it should show any other relevant info at the top of the profile page. See [Figma](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=4389-21264&mode=design&t=iK8KH5lkjPgLC0g3-0) for more details. We also need the functionality to restore a program that has been archived

Tasks:

- [ ] Create UI to view the data (including the table)
- [ ] Create backend routes to retrieve all students in a program (wait till backend reorganization is done)
- [ ] Add functionality to restore a program after it has been archived
