### ISSUE TITLE
[EPIC] - V2 Add Students Form

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#76]
The V2 student form has a new look with new features such as pdf upload, profile pic upload, and new fields for program info. Outside of the UI changes there are also some significant changes that need to made to the backend schema. See [Figma](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=4093-33939&mode=design&t=iK8KH5lkjPgLC0g3-0) for design details. BE SURE TO CLICK THE PLAY BUTTON TO VIEW ALL FEATURES. Also reference this [doc](https://docs.google.com/document/d/1pRAb2W9pVg2Pvf4bXt2HiZ5nrjeK5JQl1UiHPBMrDwY/edit?usp=sharing) on how the new backend schema should work.

Tasks:

- [ ] Update backend schema and route to match new requirements
- [ ] Create UI for new student form
- [ ] Integrate the pdf and png upload features as well as the new add program buttons
- [ ] Bring it all together
