### ISSUE TITLE
[EPIC] - Calendar (Individual Student Attendance & Billing Reports)

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#78]
Arguably one of the hardest features to implement, we need a calendar view that shows a students attendance in hours per day. Moreover, we need to create a view that shows the invoice details. To simplify the development process, this tasks is being split into two separate parts. See [Figma](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=4552-15704&mode=design&t=iK8KH5lkjPgLC0g3-0) for more details.

Calendar Tasks:

- [ ] Implement the UI calendar component, Tailwind has some dependencies that can help with this (set up meeting with @adhi0331 to discuss development)
- [ ] Ensure that users can view and modify hours each day

-------------------------------------------------------------------------------------------------------------------------

This is being removed 

Invoice Details:

- [ ] Create backend route that retrieves previous invoice data and calculates new invoice data (based on most recent program with hours recorded and program rate)
- [ ] Create UI components (use progress notes component if possible)
- [ ] Connect frontend with backend
