### ISSUE TITLE
[EPIC] - Attendance Dashboard

### ISSUE THREAD

**Issue by adhi0331** [TritonSE/PIA-Program-Manager#79]
We need a page to mark attendance. This page will have two parts 1) retrieve all absences and allow admins to mark makeup dates 2) retrieve the most recent program session and mark attendance. See [Figma](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=4629-33825&mode=design&t=iK8KH5lkjPgLC0g3-0) for more details.

Tasks:

- [ ] Create UI card components for absences and recent program sessions
- [ ] Create backend routes to mark session attendance and makeups (setup meeting with @adhi0331 to discuss schema logistics)
- [ ] Bring everything together
